<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyName>ddrun</AssemblyName>
    <Company>DDaS</Company>
    <Version>0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDaS.Server.Lib\DDaS.Server.Lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\DDaS.Tests.Web\Tools\ReqTool.cs"><Link>Tools\ReqTool.cs</Link></Compile>
    <Compile Include="..\DDaS.Tests.Web\Tools\RspTool.cs"><Link>Tools\RspTool.cs</Link></Compile>
    <Compile Include="..\DDaS.Tests.Web\Tools\LoadTool.cs"><Link>Tools\LoadTool.cs</Link></Compile>
    <Compile Include="..\DDaS.Tests.Web\Tools\MemToaster.cs"><Link>Tools\MemToaster.cs</Link></Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
