<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyName>ddrun</AssemblyName>
    <Company>DDaS</Company>
    <Version>0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDaS.Server.Lib\DDaS.Server.Lib.csproj" />
    <ProjectReference Include="..\DDaS.Tools.Web\DDaS.Tools.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
